blank_issues_enabled: false
contact_links:
  - name: Developer
    url: https://discord.com/users/571975224803721226
    about: Join discord to contact the developer
  - name: Discord server
    url: https://discord.gg/jpMhrHjWFu
    about: Join the discord server to get support and report bugs, or just to chat
